# Railway PostgreSQL Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver

# Using Railway's automatically injected environment variables!
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# Update schema automatically without dropping existing data
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
