# Local Development Configuration
dateon.ai.service-url=http://127.0.0.1:8000/predict_compatibility
spring.kafka.bootstrap-servers=localhost:9092
spring.datasource.url=jdbc:postgresql://localhost:5432/Dateon
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:4567}

# Dummy JWT Secret for local development
jwt.secret=${JWT_SECRET:YTJlOGI0ZjVjNzEyZDM2OWU4YWIxY2Q1ZjA5MTIzNDU2Nzg5MGFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIz}
# Cloudinary Dummy Config for local development
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:dummy}
cloudinary.api_key=${CLOUDINARY_API_KEY:dummy}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:dummy}
