# Render PostgreSQL Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d8i0rk3tqb8s73akigug-a:5432/dateon
spring.datasource.username=dateon_user
spring.datasource.password=E2gniem2WvTmfq4ywKmKdGDY476ePnC5

# Update schema automatically without dropping existing data
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
