# Local Development Configuration
dateon.ai.service-url=http://127.0.0.1:8000/predict_compatibility
spring.kafka.bootstrap-servers=localhost:9092
spring.datasource.url=jdbc:postgresql://localhost:5432/Dateon
spring.datasource.username=postgres
spring.datasource.password=4567

# JWT Dummy Config
jwt.secret=ZHVtbXlfand0X3NlY3JldF9tdXN0X2JlX2xvbmdfZW5vdWdoX2Zvcl9oczI1Nl9kdW1teV9qd3Rfc2VjcmV0X211c3RfYmVfbG9uZ19lbm91Z2hfZm9yX2hzMjU2

# Cloudinary Dummy Config
cloudinary.cloud_name=dummy_cloud_name
cloudinary.api_key=dummy_api_key
cloudinary.api_secret=dummy_api_secret
