# Local Development Configuration
dateon.ai.service-url=http://127.0.0.1:8000/predict_compatibility
spring.kafka.bootstrap-servers=localhost:9092
spring.datasource.url=jdbc:postgresql://localhost:5432/Dateon
spring.datasource.username=postgres
spring.datasource.password=4567
